
GET https://us-central1-ghost-444721.cloudfunctions.net/googleapis

###

POST https://us-central1-ghost-444721.cloudfunctions.net/googleapis/gmail
Content-Type: application/json

{
  "test": "gmail"
}
