POST http://localhost:3000/api/paypal/order
Content-Type: application/json

{
    "orderID": "12345",
    "amount": "100.00",
    "currency": "USD"
}

###

POST http://localhost:3000/submit

###

GET http://facebook.com

